export const API_URL = "http://localhost:8080";

export const thunkStudentTypes = {
  GETALL_STUDENT: "GETALL_STUDENT",
  GET_STUDENT: "GET_STUDENT",
};

export const thunkPracticeTypes = {
  GETALL_PRACTICE: "GETALL_PRACTICE",
  GET_PRACTICE: "GET_PRACTICE",
};

export const thunkLessonTypes = {
  GETALL_LESSON: "GETALL_LESSON",
  GET_LESSON: "GET_LESSON",
};

export const thunkCourseTypes = {
  GETALL_COURSE: "GETALL_COURSE",
  GET_COURSE: "GET_COURSE",
  GET_COURSE_BLANK: "GET_COURSE_BLANK",
  GET_COURSE_BY_TEACHER: "GET_COURSE_BY_TEACHER",
  GET_EVALUATES_BY_COURSE: "GET_EVALUATES_BY_COURSE",
};

export const thunkScheduleTypes = {
  GETALL_SCHEDULE: "GETALL_SCHEDULE",
};

export const thunkTeacherTypes = {
  GETALL_TEACHER: "GETALL_TEACHER",
  GET_TEACHER: "GET_TEACHER",
};

export const thunkDiscountTypes = {
  GETALL_DISCOUNT: "GETALL_DISCOUNT",
  GET_DISCOUNT: "GET_DISCOUNT",
};

// export const thunkBillTypes = {
//   GETALL_BILL_WAITING: "GETALL_BILL_WAITING",
//   GETALL_BILL_DELIVERING: "GETALL_BILL_DELIVERING",
//   GETALL_BILL_DELIVERED: "GETALL_BILL_DELIVERED",
//   GETALL_BILL_CANCEL: "GETALL_BILL_CANCEL"
// };

export const thunkStatisticTypes = {
  STATISTIC_ALL_PER_DAY: "STATISTIC_ALL_PER_DAY",
  STATISTIC_COURSE_INFO: "STATISTIC_COURSE_INFO",
  STATISTIC_COURSE_SELLER: "STATISTIC_COURSE_SELLER",
  STATISTIC_GENERAL: "STATISTIC_GENERAL",
};
