export const API_URL = "http://localhost:8080";

export const thunkStudentTypes = {
  GETALL_STUDENT: "GETALL_STUDENT",
  GET_STUDENT: "GET_STUDENT",
};

export const thunkPracticeTypes = {
  GETALL_PRACTICE: "GETALL_PRACTICE",
  GET_PRACTICE: "GET_PRACTICE",
};

export const thunkLessonTypes = {
  GETALL_LESSON: "GETALL_LESSON",
  GET_LESSON: "GET_LESSON",
};

export const thunkCourseTypes = {
  GETALL_COURSE: "GETALL_COURSE",
  GET_COURSE: "GET_COURSE",
  GET_COURSE_TYPE: "GET_COURSE_TYPE",
};

export const thunkScheduleTypes = {
  GETALL_SCHEDULE: "GETALL_SCHEDULE",
  GETALL_SCHEDULE_BY_LESSON: "GETALL_SCHEDULE_BY_LESSON",
};

// export const thunkFeedbackTypes = {
//   GETALL_FEEDBACK: "GETALL_FEEDBACK",
//   GET_FEEDBACK: "GET_FEEDBACK",
// };

export const thunkTestTypes = {
  GETALL_TEST: "GETALL_TEST",
  GET_TEST: "GET_TEST",
};

// export const thunkBillTypes = {
//   GETALL_BILL_WAITING: "GETALL_BILL_WAITING",
//   GETALL_BILL_DELIVERING: "GETALL_BILL_DELIVERING",
//   GETALL_BILL_DELIVERED: "GETALL_BILL_DELIVERED",
//   GETALL_BILL_CANCEL: "GETALL_BILL_CANCEL"
// };

// export const thunkStatisticTypes = {
//   STATISTIC_USER: 'STATISTIC_USER',
//   STATISTIC_FIVE_USER: 'STATISTIC_FIVE_USER',
//   STATISTIC_FIVE_TRANSACTION: 'STATISTIC_FIVE_TRANSACTION',
//   STATISTIC_PRODUCT: 'STATISTIC_PRODUCT',
//   STATISTIC_BILL: 'STATISTIC_BILL',
//   STATISTIC_SALE: 'STATISTIC_SALE',
//   STATISTIC_REVENUE: 'STATISTIC_REVENUE',
//   STATISTIC_TRANSACTION: 'STATISTIC_TRANSACTION',
//   STATISTIC_TIME_USER: 'STATISTIC_TIME_USER',
//   STATISTIC_SALE_PRODUCT: 'STATISTIC_SALE_PRODUCT',
//   STATISTIC_SALE_DATE: 'STATISTIC_SALE_DATE',
// };