export const API_URL = "http://localhost:8080";

export const thunkStudentTypes = {
  GETALL_STUDENT: "GETALL_STUDENT",
  GET_STUDENT: "GET_STUDENT",
};

export const thunkPracticeTypes = {
  GETALL_PRACTICE: "GETALL_PRACTICE",
  GET_PRACTICE: "GET_PRACTICE",
  GET_PRACTICE_SCORE: "GET_PRACTICE_SCORE",
  GET_PRACTICE_SCORE_LESSON: "GET_PRACTICE_SCORE_LESSON",
  GET_QUESTION: "GET_QUESTION",
};

export const thunkLessonTypes = {
  GETALL_LESSON: "GETALL_LESSON",
  GET_LESSON: "GET_LESSON",
};

export const thunkCourseTypes = {
  GETALL_COURSE: "GETALL_COURSE",
  GET_COURSE: "GET_COURSE",
  GET_COURSE_TYPE: "GET_COURSE_TYPE",
  GET_COURSE_TYPING: "GET_COURSE_TYPING",
  GET_ALL_COURSES_TYPE: "GET_ALL_COURSES_TYPE",
};

export const thunkTeacherTypes = {
  GETALL_TEACHER: "GETALL_TEACHER",
  GET_TEACHER: "GET_TEACHER",
};

export const thunkFeedbackTypes = {
  GETALL_FEEDBACK: "GETALL_FEEDBACK",
  GET_FEEDBACK: "GET_FEEDBACK",
};

export const thunkBillTypes = {
  GETALL_BILL: "GETALL_BILL",
  GET_BILL: "GET_BILL",
};

export const thunkCourseLearningTypes = {
  GETALL_BLOG: "GETALL_COURSE_LEARNING",
  GET_COURSE_LEARNING: "GET_COURSE_LEARNING",
  GET_COURSE_LIKED: "GET_COURSE_LIKED",
};

export const thunkBlogTypes = {
  GETALL_BLOG: "GETALL_BLOG",
  GETALL_BLOG_BY_USER: "GETALL_BLOG_BY_USER",
  GET_BLOG: "GET_BLOG",
  GET_BLOG_BY_USER: "GET_BLOG_BY_USER",
  GET_COMMENT: "GET_COMMENT",
};

export const thunkFlashcardTypes = {
  GETALL_FLASHCARD: "GETALL_FLASHCARD",
  GET_FLASHCARD: "GET_FLASHCARD",
};

export const thunkWordTypes = {
  GETALL_WORD: "GETALL_WORD",
  GET_WORD: "GET_WORD",
};

export const thunkTestTypes = {
  GET_TEST: "GET_TEST",
  GET_DETAIL_TEST: "GET_DETAIL_TEST",
};

// export const thunkStatisticTypes = {
//   STATISTIC_USER: 'STATISTIC_USER',
//   STATISTIC_FIVE_USER: 'STATISTIC_FIVE_USER',
//   STATISTIC_FIVE_TRANSACTION: 'STATISTIC_FIVE_TRANSACTION',
//   STATISTIC_PRODUCT: 'STATISTIC_PRODUCT',
//   STATISTIC_BILL: 'STATISTIC_BILL',
//   STATISTIC_SALE: 'STATISTIC_SALE',
//   STATISTIC_REVENUE: 'STATISTIC_REVENUE',
//   STATISTIC_TRANSACTION: 'STATISTIC_TRANSACTION',
//   STATISTIC_TIME_USER: 'STATISTIC_TIME_USER',
//   STATISTIC_SALE_PRODUCT: 'STATISTIC_SALE_PRODUCT',
//   STATISTIC_SALE_DATE: 'STATISTIC_SALE_DATE',
// };